### ISSUE TITLE
How to set set button height ?

### ISSUE THREAD

**Issue by azizimusa** [jlhonora/multistatetogglebutton#11]
I can't find it in the documentation.

**Comment by jlhonora** [comment]
Try something like this:

```
<org.honorato.multistatetogglebutton.MultiStateToggleButton
        android:layout_width="wrap_content"
        android:layout_height="100dip" />
```

**Comment by azizimusa** [comment]
But the text inside it won't vertically centered.

**Comment by jlhonora** [comment]
Copying the project is definitely the easiest way to tweak it for your preference.

Anyhow, with my example the buttons are indeed vertically centered:

![victara_retlalpe23 32-14 2jlh11182015100715](https://cloud.githubusercontent.com/assets/1577721/11241767/4179204c-8ddc-11e5-952a-006e3f31c201.png)
