### ISSUE TITLE
I can't change color of button.

### ISSUE THREAD

**Issue by nawaminp** [jlhonora/multistatetogglebutton#13]
How can i chage a color of buttons?

**Comment by jlhonora** [comment]
The best way for now is to clone the repo and change it directly. I'm working on alternatives to support this in the XML, but for now that's the best option. Suggestions are welcome :)

**Comment by jlhonora** [comment]
The colors are now inherited from `colorPrimary` and `controlColorNormal`, defined in your style. Upgrade to `0.1.4` and check the Readme for more usage information.

Let me know if it works for you.

**Comment by jlhonora** [comment]
Closing this since there are now multiple alternatives for setting the color. Please reopen if the current scheme doesn't fit your needs.
