### ISSUE TITLE
How to set listener when specific state is toggled

### ISSUE THREAD

**Issue by eriuzo** [jlhonora/multistatetogglebutton#17]
for example when i click "doge" i want to show a toast "doge". There is no setOnToggle or setOnSpecificButtonSelected or something.

**Comment by eriuzo** [comment]
sorry i'm dumb, found setOnValueChangedListener in base ToggleButton.

**Comment by jlhonora** [comment]
No worries! No question is dumb. Reach out if you have any. Happy coding!
