### ISSUE TITLE
Colors set programmatically don't change until button pressed

### ISSUE THREAD

**Issue by atomjack** [jlhonora/multistatetogglebutton#22]
Setting colors programmatically on a Toggle Button that was defined in XML doesn't change the colors of the buttons until they are pressed.

**Comment by jlhonora** [comment]
Do you have an example app you could share? In the example app there's a `MultiStateToggleButton` whose colors are set dynamically (the green-gray one), works fine.

Thanks a lot in advance.

**Comment by atomjack** [comment]
Hmm ya know I just created a test project and tried it out and it seems to work just fine. I must have been mistaken, sorry!
