### ISSUE TITLE
Error Failed to resolve: org.honorato.multistatetogglebutton:multistatetogglebutton:0.2.1

### ISSUE THREAD

**Issue by aletandil** [jlhonora/multistatetogglebutton#23]
I added the line  compile 'org.honorato.multistatetogglebutton:multistatetogglebutton:0.2.1' to my build file but I get the next error:
"Error Failed to resolve: org.honorato.multistatetogglebutton:multistatetogglebutton:0.2.1"

**Comment by jlhonora** [comment]
Do you have `jcenter` included in the repositories section of your base
`build.gradle`? Also I'd recommend taking a look at the example folder.

Let me know if the problem persists.

**Comment by aletandil** [comment]
yes, I have the jcenter included
Anything else that I need to check?
Thanks

**Comment by jlhonora** [comment]
Sorry for the delay.

I just updated the example app to use bintray's lib (the one you fail to resolve). I suggest that you take a look at that and compare it to your setting to check if you're missing something.

**Comment by eriknyk** [comment]
the resource is still broken, couldn't to resolve

![image](https://cloud.githubusercontent.com/assets/205721/25507091/ab4f6a62-2b6f-11e7-9d1e-6f92027675a7.png)
