### ISSUE TITLE
How do you change textsize and textmargin?

### ISSUE THREAD

**Issue by dikkemulle** [jlhonora/multistatetogglebutton#24]
I implement this button in a horizontal linear layour and it works great.
However, as 1 of the words in the button is too long, its spread over 2 lines.
This is not visually pleasing, and would like to change, or the textsize, or the padding of the text inside of the button.

How can I do this?

**Comment by dikkemulle** [comment]
Found it.
It was very obvious, you just take the children of the multistatebutton, cast them to button and change the textsize!

`   for(int i = 0; i <mThreeStateButton.getChildCount(); i++){
                    Button button = (Button) mThreeStateButton.getChildAt(i);
                    button.setIncludeFontPadding(false);
                    button.setTextSize(TypedValue.COMPLEX_UNIT_DIP,7);

                }`

setIncludeFondPadding removes the padding of the text.

**Comment by jlhonora** [comment]
Great! If you have a proposal on how to do it in XML instead of changing the code itself I'd be glad to hear it.

**Comment by kevindekemele** [comment]
I will look into this when I have the time, probably have to create some new variables in the mstb namespace?
