### ISSUE TITLE
Corners to button

### ISSUE THREAD

**Issue by Yokeshthebouncer** [jlhonora/multistatetogglebutton#26]
I Need to set a corner radius to the whole button. But its not reflecting , even i tried using in both java and xml, can someone help me out?

**Comment by jlhonora** [comment]
Did you try modifying the button's drawables? You'll probably need to specify the `corners` attribute. Have a look at http://developer.android.com/guide/topics/resources/drawable-resource.html#Shape for the specific syntax

**Comment by Yokeshthebouncer** [comment]
Thank You. Got fixed.
