### ISSUE TITLE
how can i get values when multiple?

### ISSUE THREAD

**Issue by gustavomc** [jlhonora/multistatetogglebutton#34]
is there a way to get values when multiple?

**Comment by jlhonora** [comment]
Hi Gustavo,

I'm not really sure what you mean, would you mind sharing more details?

**Comment by gustavomc** [comment]
when you set a MultiStateToggleButton to multiselect, how can you get all values selected in an array?

**Comment by jlhonora** [comment]
Oh, sure, `getStates` returns a boolean array with the status of each button.
