### ISSUE TITLE
Button margin

### ISSUE THREAD

**Issue by felipecds** [jlhonora/multistatetogglebutton#37]
Please, is there a way of adding button margins using your library?. 

I tried a solution based on another issue, changing the margin/padding of buttons in my activity code, but no luck.

**Comment by felipecds** [comment]
Edit:

I finally figured out on how to change the margin using code:

```java
for (int i = 0; i < mTgSituacao.getChildCount(); i++) {
            ViewGroup.MarginLayoutParams p = (ViewGroup.MarginLayoutParams)((Button)mTgSituacao.getChildAt(i)).getLayoutParams();
            p.setMargins(p.leftMargin, p.topMargin, (int)Util.convertDpToPixel(8, AlertaActivity.this), p.rightMargin);
            ((Button)mTgSituacao.getChildAt(i)).requestLayout();
        }
```

Now the challeng is how to remove the background artifact showed here:

![image](https://cloud.githubusercontent.com/assets/5657750/16414268/114fc124-3d0d-11e6-82d6-b3168693129b.png)

Any help would be appreciated =)

**Comment by felipecds** [comment]
Edit 2:

It's done: create a drawable and set a <solid> with @android:color/transparent

```xml
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android">
    <solid android:color="@android:color/transparent" />
</shape>
```

and write this peace of code

```java
mToogle.setBackgroundResource(R.drawable.your_awesome_drawable);
```

**Comment by jlhonora** [comment]
Hi Felipe,

Sorry for the delay, I'm glad you figured it out.

**Comment by felipecds** [comment]
No problem. I'm using this lib in a project, and the user's design need the margin between buttons. You have an awesome lib, and I'm thinking in contribute to it, giving the user the possibility to add margin between buttons.


Do you think that is it a hard work?


________________________________
