### ISSUE TITLE
How to make all toggle buttons the same size

### ISSUE THREAD

**Issue by adelburekovic** [jlhonora/multistatetogglebutton#4]
Is it possible to make all toggle buttons in multistate view the same size. Problem occurs if text on one toggle button is longer than on another one.

**Comment by jlhonora** [comment]
They should be the same size, since each one is given `layout_weight=1`. How are you loading the elements? Could you share some of your code?

**Comment by adelburekovic** [comment]
<LinearLayout
          android:layout_width="match_parent"
          android:weightSum="4"
          android:orientation="horizontal"
          android:layout_height="match_parent">

          <TextView
              android:layout_width="0dp"
              android:layout_weight="1"
              android:layout_height="match_parent"
              android:text="Options"
              android:background="@android:color/transparent"
              android:textColor="@color/green"
              android:padding="5dp"
              android:layout_gravity="center_vertical"
              android:gravity="center"
              android:id="@+id/filter_looking_for"
              />

          <com.trueview.ui.MultiStateToggleButton
              android:layout_width="0dp"
              android:layout_weight="3"
              android:id="@+id/switchDiscovery"
              android:gravity="center_horizontal"
              android:entries="@array/discovery_arrays"
              android:layout_marginTop="5dp"
              android:layout_marginRight="20dp"
              android:layout_marginLeft="5dp"
              android:layout_marginBottom="5dp"
              android:layout_height="wrap_content"
              android:layout_below="@+id/view"
              android:layout_centerHorizontal="true">
          </com.trueview.ui.MultiStateToggleButton>
    
      </LinearLayout>

**Comment by adelburekovic** [comment]
<code> 
<LinearLayout
          android:layout_width="match_parent"
          android:weightSum="4"
          android:orientation="horizontal"
          android:layout_height="match_parent">

          <TextView
              android:layout_width="0dp"
              android:layout_weight="1"
              android:layout_height="match_parent"
              android:text="Options"
              android:background="@android:color/transparent"
              android:textColor="@color/green"
              android:padding="5dp"
              android:layout_gravity="center_vertical"
              android:gravity="center"
              android:id="@+id/filter_looking_for"
              />

          <com.trueview.ui.MultiStateToggleButton
              android:layout_width="0dp"
              android:layout_weight="3"
              android:id="@+id/switchDiscovery"
              android:gravity="center_horizontal"
              android:entries="@array/discovery_arrays"
              android:layout_marginTop="5dp"
              android:layout_marginRight="20dp"
              android:layout_marginLeft="5dp"
              android:layout_marginBottom="5dp"
              android:layout_height="wrap_content"
              android:layout_below="@+id/view"
              android:layout_centerHorizontal="true">
          </com.trueview.ui.MultiStateToggleButton>
    
      </LinearLayout>
</code>

![img](https://cloud.githubusercontent.com/assets/7288092/6212572/24cd8b2c-b5e7-11e4-84ac-53881a47da6e.PNG)

I have multistatebutton in simple layout with weight = 4. And multistatebtn has weight 3 for width. As you can see in the picture these two elements don't have the same width. I would appreciate any tips.

**Comment by adelburekovic** [comment]
I think i found a solution @jlhonora. You were correct that there was weight = 1 for each element but width was not "0dp" but "wrap content" so that weight didn't have any effect. 
I solved it by simply adding sumWeight = 2 to mainLayout and width = "0dp" to left and right layouts. (I have 2 buttons)

**Comment by jlhonora** [comment]
Great! Sorry I didn't have time to check it out sooner. Nice design BTW...
