### ISSUE TITLE
Not possible use ColorInt, only ColorRes

### ISSUE THREAD

**Issue by mtrakal** [jlhonora/multistatetogglebutton#41]
`ColorInt` is much more universal, you can chnage `ColorRes` to `ColorInt`, but not vice versa.

`setColor(@ColorInt int color, @ColorInt int color2);` would be useful :)

**Comment by mtrakal** [comment]
Sorry, I'm stupid, there is a `setColors`...  :)

**Comment by jlhonora** [comment]
No question is stupid!

Thanks for your other contribs.
