### ISSUE TITLE
How to style?

### ISSUE THREAD

**Issue by SHAD0WF4X** [jlhonora/multistatetogglebutton#8]
Hi, I used the examples, but it looks like this:

![bug](https://cloud.githubusercontent.com/assets/7324718/9932603/94775434-5d45-11e5-91c6-2ed50451b784.png)

How can I design them like the picture?

**Comment by jlhonora** [comment]
Wow, sorry about that. Can you share the build.gradle section where your import the library?

**Comment by jlhonora** [comment]
I just released 0.1.3, should fix this. Try importing with

```
compile 'org.honorato.multistatetogglebutton:multistatetogglebutton:0.1.3'
```

**Comment by SHAD0WF4X** [comment]
That fixed it. Got any examples on changing textcolors, selectedTextColors, backgroundColors and selectedBackgroundColors?

**Comment by jlhonora** [comment]
Great!

If you want to style it I recommend you to fork the repo and edit the styling directly. You'll have to reference the project locally though:

```
dependencies {
    compile project(':multistatetogglebutton')
}
```
