### ISSUE TITLE
Can't import compile 'org.honorato.multistatetogglebutton:multistatetogglebutton:0.1.2'

### ISSUE THREAD

**Issue by willf80** [jlhonora/multistatetogglebutton#9]
Hello,
I can't import **compile 'org.honorato.multistatetogglebutton:multistatetogglebutton:0.1.2'** in my project. Android studio give me this message : Failed to resolve. Can you help me please ?

Best regards

**Comment by jlhonora** [comment]
Hi, sorry to hear that. Can you share your build.gradle file please?
